import * as fs from 'fs-extra';
import * as path from 'path';
import { execSync } from 'child_process';
import { glob } from 'glob';

/**
 * External command execution utilities
 */

/**
 * Runs external code generation tools
 */
export async function runCodeGeneration(outputDir: string, generatedFiles: Set<string>): Promise<void> {
  console.log('Running code generation...');

  const srcDir = path.join(outputDir, 'src');
  const abiDir = path.join(outputDir, 'abi');

  // Remove existing generated directories
  const srcAbiDir = path.join(srcDir, 'abi');
  const modelDir = path.join(srcDir, 'model');
  
  if (await fs.pathExists(srcAbiDir)) {
    await fs.remove(srcAbiDir);
  }
  if (await fs.pathExists(modelDir)) {
    await fs.remove(modelDir);
  }

  // Generate ABI types
  const abiFiles = await glob('*.json', { cwd: abiDir });
  const abiGlob = abiFiles.map(file => `./abi/${file}`).join(' ');
  
  try {
    execSync(`npx @subsquid/evm-typegen ./src/abi ${abiGlob} --multicall`, {
      cwd: outputDir,
      stdio: 'inherit'
    });
    
    // Track the entire abi directory as generated
    generatedFiles.add('src/abi');
  } catch (error) {
    console.warn('Warning: Failed to run squid-evm-typegen:', error);
  }

  // Generate TypeORM models
  try {
    execSync('npx @subsquid/typeorm-codegen', {
      cwd: outputDir,
      stdio: 'inherit'
    });
    
    // Track the entire model directory as generated
    generatedFiles.add('src/model');
  } catch (error) {
    console.warn('Warning: Failed to run squid-typeorm-codegen:', error);
  }
}

/**
 * Installs npm dependencies
 */
export async function installDependencies(outputDir: string, generatedFiles: Set<string>): Promise<void> {
  console.log('Installing dependencies (may take a while)...');
  
  try {
    execSync('npm install --progress=false', {
      cwd: outputDir,
      stdio: 'inherit'
    });
    
    // Track files that might be generated by npm install
    const packageLockPath = path.join(outputDir, 'package-lock.json');
    if (await fs.pathExists(packageLockPath)) {
      generatedFiles.add('package-lock.json');
    }
    
    // Track node_modules directory
    const nodeModulesPath = path.join(outputDir, 'node_modules');
    if (await fs.pathExists(nodeModulesPath)) {
      generatedFiles.add('node_modules');
    }
  } catch (error) {
    console.warn('Warning: Failed to install dependencies:', error);
  }
}
